version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_api
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  mysql:
    image: mysql:5.7
    container_name: mydb_mysql2
    command: mysqld --user=root
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 6604:3306
    environment:
      - MYSQL_ROOT_HOST=127.0.0.1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=shortener
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10